name-template: 'Draft for develop8.1'
tag-template: 'Draft for develop8.1'
filter-by-commitish: true
commitish: develop8.1
version-template: 'Draft for develop8.1'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
template: |
  ## What’s Changed
  $CHANGES
